modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/CAS-ual-TY/Spells-And-Shields-x-Origins/issues"


[[mods]] #mandatory
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="https://github.com/CAS-ual-TY/Spells-And-Shields-x-Origins"
    logoFile="logo.png"
    credits="Mojang and the Minecraft Forge Team"
    authors="${mod_authors}"
    description='''${mod_description}'''

[[dependencies.spells_and_shields_x_origins]]
    modId="spells_and_shields"
    mandatory=true
    versionRange="[1.18.2-2.12.0,1.19.2-3.0.0)"
    side="BOTH"
[[dependencies.spells_and_shields_x_origins]]
    modId="origins"
    mandatory=true
    versionRange="[1.18.2-1.5.0.1,)"
    side="BOTH"